### PR TITLE
remove unused

### PR DESCRIPTION
**Pull request by drhideg**
- remove unused from TopAppBar.js
- remove unused from translation files
- add `__translation__` comment to translation files
- add comment to languages.js

### CODE REVIEW

**Comment by benzino77** [comment]
What for is this property `__translation__` needed?

**Comment by drhideg** [comment]
> What for is this property `__translation__` needed?

Can't do comment in JSON files to see what is it, otherwise it can be removed.

**Comment by benzino77** [comment]
Do we need comments in those files?

**Comment by drhideg** [comment]
You are accurate and precise, I tought you want to see something there.
Removed.

**Pull request merged**
