### PR TITLE
xversion: Allow features without description

### PR DESCRIPTION
**Pull request by drhideg**

### CODE REVIEW

**Comment by benzino77** [comment]
Well, this is a part of "code cleanup" I mentioned before. I want every feature to have all "fields" even if for particular feature it is null/empty etc. (just like `description` for "meta" features).
In that case this change:
```
availableFeatures.sort((a , b) => {
    if (!a.description || a.description === ''){
        return -1;
    } else if (!b.description || b.description === ''){
        return 1;
    } else {
        return allMessages[currentLocale][a.description].localeCompare(allMessages[currentLocale][b.description], currentLocale, { sensitivity: 'base' });
    }
});
```
is still needed? I think features are sorted in proper way... or I'm missing something?

**Comment by drhideg** [comment]
In this case the https://github.com/benzino77/tasmocompiler/pull/129 will hurt you, i removed all empty object :) Of course it can be removed witt the `, currentLocale, { sensitivity: 'base' }` part, Just put there to be complete.

**Comment by drhideg** [comment]
Continued on https://github.com/benzino77/tasmocompiler/pull/129.

**Comment by benzino77** [comment]
I heaven't seen #129 before and that's why I had doubts . Now I see the bigger picture. Let's continue discussion on the #129 as you suggested.

**Pull request closed without merging**
