### PR TITLE
Try to fix missing placeholder in Custom parameters step

### PR DESCRIPTION
**Pull request by drhideg**
Meanwhile I was confused how can I avoid delete manually added custom defines.

If i add `#define USE_WHATEVER` line to custom parameters, the i go back to check/uncheck any of the feature which uses custom parameters, it will delete manually added lines. In this example the `#define USE_WHATEVER` will not be there.

### CODE REVIEW

**Comment by bovirus** [comment]
@drhideg 

Can this patch fix these issue

https://github.com/benzino77/tasmocompiler/issues/166

**Comment by drhideg** [comment]
@bovirus No, it does not help on that.

**Comment by benzino77** [comment]
But this will only remove white characters from the string. Or am I wrong?

**Comment by benzino77** [comment]
To get functionality/behavior you've mentioned (not loosing manually entered custom parameters) there should be dedicated text field for that (I think). In other case you will have to do many operations checking which parts of custom parameters comes from chosen features and the rest can be considered as entered manually. But one could always enter custom `#defines` in the middle of prepopulated settings from selected features.

**Comment by drhideg** [comment]
Yes, this is really only for the whitespaces, let placeholder show. I do not play there a lot and just realized that behaviour.

**Comment by drhideg** [comment]
I was confused with the reverts and now trim() somehow missing from source :)

**Comment by benzino77** [comment]
I have no idea why. PR was merged after your revert revert this change... at least I think so

**Comment by benzino77** [comment]
That was your commit  5a188da9f8544ef48e30d1bca0d52f756fcf3493 six days ago... so it was merged after you introduced `trim()` that's why it is missing

**Comment by benzino77** [comment]
Commit history is here: https://github.com/benzino77/tasmocompiler/commits/master

**Comment by benzino77** [comment]
image

**Comment by drhideg** [comment]
I have no doubt that I caused the error. What I learned is patches have no place in my master so I have clean source to make another branch for patches.

**Pull request merged**
