### PR TITLE
Add option to build for ESP8266_2M1M

### PR DESCRIPTION
**Pull request by claymore666**
As a followup to [pull request #258](https://github.com/benzino77/tasmocompiler/pull/258), here we go with the ESP8266_2M1M feature. Merged all changes into development branch and verified that the code is actually running.

### CODE REVIEW

**Comment by claymore666** [comment]
sorry for the mess with so many commits. i payed some attention that your development changes are still in the code. The comparison of the file changes is looking good to me as does the comparison of the running GUI with and without this pull req.

**Comment by benzino77** [comment]
I've been a litte bit lost with all the commits ;) so I pick the essence of this PR and implement proposed changes. Code is already pushed. I will build new docker image for `development` branch. THANKS A LOT!!!!!!

**Comment by claymore666** [comment]
Yeah me too. Aparently me developing on Master and tgrn reverting to dev caused the mess. Next time There will. Be only one commit, sorry again.

**Comment by benzino77** [comment]
There is no need to be sorry. I'm really thankful for your contribution!

**Pull request closed without merging**
