### PR TITLE
Add CODE_IMAGE_STR

### PR DESCRIPTION
**Pull request by drhideg**
This one implements the `with name` from https://github.com/benzino77/tasmocompiler/discussions/167#discussioncomment-643834

### CODE REVIEW

**Comment by benzino77** [comment]
Have a look here: https://github.com/arendst/Tasmota/blob/674509a56e6226b7450acf5cb2c13a666c4ef7c4/tasmota/tasmota.ino#L200

Image name string should be max 33 bytes long.
```bash
echo -n "TasmoCompiler-esp32odroid-go" | wc -c
28
```
so we have 5 characters left (4 to be on good side). If in the future we will have another board which name will be longer then `esp32odroid-go` we will have a problem (I think).  This value can change in Tasmota itself - today Theo and dev team decided that it is 33 bytes but it can be changed to 25 or 66 in the future.
A better approach would be checking what is the current maximal allowed length, then based on that build the name of the image. There should be a helper function to find out current maximal length. If the function cannot determine this length (i.e. the location af that information has changed or the name of variable has changed), the `CODE_IMAGE_STR` should not be added until proper changes on TasmoCompiler side are introduced.
Have a look how Tasmota version is found by [getTasmotaVersion](https://github.com/benzino77/tasmocompiler/blob/88c0d9cbd261d40dbc91b2bb70487b66681dd37a/server/compile/compile.js#L15) function.

**Comment by drhideg** [comment]
You are right we could respect it. But you can not change any if user put this in the Custom parameters field. It is compiled into the binary (I put there a 50 char long string) and it is truncated when it is turned into variable with `snprintf_P` at https://github.com/arendst/Tasmota/blob/674509a56e6226b7450acf5cb2c13a666c4ef7c4/tasmota/tasmota.ino#L350
```
#ifdef CODE_IMAGE_STR
  #undef CODE_IMAGE_STR
#endif
#define CODE_IMAGE_STR "12345678901234567890123456789012345678901234567890"
```
I do not have any esp32 based module, but on a Wemos D1 mini console and information tab looks good:
```
11:47:06.388 CMD: status 2
11:47:06.395 RSL: STATUS2 = {"StatusFWR":{"Version":"9.4.0.2(1234567890123456789012345678901","BuildDateTime":"2021.04.28 10:30:02","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"407/699"}}
```
```
Program verzió | 9.4.0.2(1234567890123456789012345678901
```

**Comment by benzino77** [comment]
Sure we have no control of what user can input in Custom Parameters step... but it is not our problem ;)
Everything from Text field in custom parameters step is written at the end of `user_config_override.h` file so it will eventually override any previous `#define` statemetnts
What we could/should do is to build image with nice, proper, not truncated, looking good and informative `CODE_IMAGE_STR`.

**Comment by drhideg** [comment]
How could be this sentence better? (with manually modified limit)
`codeImageStr(TasmoCompiler-esp8266[21]) length exceeded image_name[32] limit.`

I do not want to force it as an error and stop compiling, but it will be useful to see these warnings on the client side. How can I achieve that? Of course easily :)

**Comment by benzino77** [comment]
It depends where do you want to display this message. On backend side it'w enough to use `debug` function (rather do not use `console.*`). On client side... well you need to send this information via WebSocket and `socket.emit` function.

**Comment by benzino77** [comment]
To push information to the browser you have to use WebSocket and `socket.emit` function:
```javascript
const getImageName = (socket, name) => {
  const fileExists = fs.pathExistsSync(tasmotaInoFile);
  const imageNameRegexp = /char image_name\[(.*)\];/gm;
  const codeImageStr = `TasmoCompiler-${name}`;
  let retValue = '';
  let messageToEmit = `${tasmotaInoFile} does not exists. The CODE_IMG_STR will not be set.`;

  if (fileExists) {
    const file = fs.readFileSync(tasmotaInoFile, {
      encoding: 'utf8',
      flag: 'r',
    });

    const match = [...file.matchAll(imageNameRegexp)];
    messageToEmit = `Cannot find image_name length in ${tasmotaInoFile}.`;

    if (match[0]) {
      // take care of space for null termination
      const maxLength = parseInt(match[0][1]) - 1;
      messageToEmit = `codeImageStr(${codeImageStr}[${codeImageStr.length}]) length exceeded image_name[${maxLength}] limit.`;

      if (codeImageStr.length <= maxLength) {
        retValue = `#ifdef CODE_IMAGE_STR\n  #undef CODE_IMAGE_STR\n#endif\n#define CODE_IMAGE_STR "${codeImageStr}"\n\n`;
        messageToEmit = `CODE_IMAGE_STR set to "${codeImageStr}"}`;
      }
    } //findImageName
  } //fileExists

  socket.emit('message', messageToEmit);
  return retValue;
};
```
Of course you have to populate `socket` object down to the function you want to use it in.
To display information on backend side use `debug` function instead.

PS.
I haven't tested this code. 
PS2.
From some time i just don't like `else` statements. I can't tell why but I just don't like them. `else` statements makes code less... readable(?).

**Comment by drhideg** [comment]
Your code works well with the modified call
```javascript
`${getImageName(socket, features.board.name)}` +
```
Added newline and remove message on success:
```javascript
const getImageName = (socket, name) => {
  const fileExists = fs.pathExistsSync(tasmotaInoFile);
  const imageNameRegexp = /char image_name\[(.*)\];/gm;
  const codeImageStr = `TasmoCompiler-${name}`;
  let retValue = '';
  let messageToEmit = `${tasmotaInoFile} does not exists. The CODE_IMG_STR will not be set.\n`;

  if (fileExists) {
    const file = fs.readFileSync(tasmotaInoFile, {
      encoding: 'utf8',
      flag: 'r',
    });

    const match = [...file.matchAll(imageNameRegexp)];
    messageToEmit = `Cannot find image_name length in ${tasmotaInoFile}.\n`;

    if (match[0]) {
      // take care of space for null termination
      const maxLength = parseInt(match[0][1]) - 1;
      messageToEmit = `codeImageStr(${codeImageStr}[${codeImageStr.length}]) length exceeded image_name[${maxLength}] limit.\n`;

      if (codeImageStr.length <= maxLength) {
        retValue = `#ifdef CODE_IMAGE_STR\n  #undef CODE_IMAGE_STR\n#endif\n#define CODE_IMAGE_STR "${codeImageStr}"\n\n`;
        messageToEmit = '';
      }
    } // findImageName
  } // fileExists

  socket.emit('message', messageToEmit);
  return retValue;
};
```
Without socketIO, i tried #warning preprocessor, but looks ugly. It is in the output from every place where `user_config_override.h` included.

**Comment by benzino77** [comment]
Could you update the PR code? I will have a look at it as a whole.

**Comment by drhideg** [comment]
Updated.

**Pull request merged**
