### PR TITLE
ADD ghcr.io image creation to workflow

### PR DESCRIPTION
**Pull request by rapejim**
Now with Github Container Registry (ghcr.io) too:
- Added extract metadata step (for automated labels and tags of images)
- Changed build&push step from a simple/manual "run" to official docker action.
(All separated by branch selected)

### CODE REVIEW

**Comment by benzino77** [comment]
Could you please make this PR to `development` branch?
Why do we need another/additional registry?

**Comment by rapejim** [comment]
Por supuesto, lo cambio a la rama "development".

Docker tiene limites para las cuentas gratuitas, por ejemplo la politica de retención elimina una imagen si no se le hace pull/push en 6 meses. Sé que es mucho tiempo, pero supongo que tampoco está de más ofrecer el registro adicional de Github que es tambien donde está el código fuente, 😅.

**Comment by rapejim** [comment]
I have seen that I am doing the PR from my master branch, do you want me to change the source to development in my repository?

**Comment by benzino77** [comment]
> I have seen that I am doing the PR from my master branch, do you want me to change the source to development in my repository?

I think that is a good idea.

**Pull request closed without merging**
