### PR TITLE
Use Python 3.x for gitpod

### PR DESCRIPTION
**Pull request by Jason2866**
Python 2.7 is out of support

### CODE REVIEW

**Comment by benzino77** [comment]
Today I update the code to fix issue #31 .
All tests on gitpod and docker images went fine, but as I can see on platformio docs site the python 2.7 and **3.5+** is supported. I think I have to move to 3.7 version of python for gitpod builds and in docker images. I will do some tests. Thanks!

**Comment by Jason2866** [comment]
If you are already on it. Please remove core 2.5 support. This core has a big bug.
Core 2.3.0 and 2.4.2 are not supported anymore from Tasmota side.
So it can be that building Tasmota with this cores will fail or produce unwanted behavior in usage
Consider adding the feature freeze stage Tasmota version. See https://github.com/arendst/Tasmota/blob/development/platformio_override_sample.ini#L180 
Probably the next release of Tasmota will be build with that version if core 2.7.x is not released 
at this time. Planned release date for next Tasmota version is 21.03.2020

**Comment by benzino77** [comment]
Remove 2.5 core support - sure, it won't be a problem.
Remove core 2.3.0 and 2.4.2 will lead to the situation that I have to remove support for version 6.x which I thing is not a big problem because it is two releases behind current and probably not so many people will try to compile this version.
Question: version 7.x will compile with "tasmota stage" and core 2.6.1 version? If so, I will probably leave only version 7.x and 8.x to select.

Jason! Thanks for your involvement!

PS. There is already python3 branch so you can test that if you want.

**Comment by Jason2866** [comment]
Yes version 7.x and newer compile with all core versions >= 2.6.1 including feature/stage builds

**Comment by benzino77** [comment]
I think it is done. 
- remove core 2.3.x, 2.4.x, 2.5.x support
- remove support for tasmota version prior v7
- add support for core_stage (coming next release of arduino core)

**Pull request closed without merging**
