### PR TITLE
Update AvailableFeatures.js

### PR DESCRIPTION
**Pull request by drhideg**
Tasmota use SUPPORT_IF_STATEMENT instead of USE_IF_STATEMENT
https://tasmota.github.io/docs/Rules/#expressions-in-rules

### CODE REVIEW

**Comment by benzino77** [comment]
You are right! Thanks for that. Could you please bump version in `package.json` to the value 2.4.9. I will then merge this request.

**Comment by drhideg** [comment]
Done! And thanks for your good work on this tool!

**Comment by benzino77** [comment]
Thanks!

**Comment by benzino77** [comment]
Maybe you want to contribute in translating TasmoCompiler to your native language?

**Comment by drhideg** [comment]
As you wish, i added it in #95

**Pull request merged**
