### PR TITLE
Update English language - added Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@benzino77 

English - Small changes
Italian - Add language

Please merge

### CODE REVIEW

**Comment by benzino77** [comment]
You have to edit one more file. The procedure is described in [TRANSLATION.md](https://github.com/benzino77/tasmocompiler/blob/master/TRANSLATION.md) file.
You don't have to make another Pull Request. Just edit your branch, commit and push to your repository.

Thanks for the translation!

**Comment by bovirus** [comment]
@benzino77 

OK. I will re-upload the PR.

I jI have a doubt.

Why EN/ES use "locale" and "PL/IT" use "locales"?
I believe that should be all "locale" or "locales".

import **_locale_**ES from '../locales/es.json';
import **_locale_**IT from '../locales/it.json';
import **_locales_**PL from '../locales/pl.json'; 

export const allMessages = 
  en: **_locale_**EN,
  es: **_locale_**ES,
  pl: **_locales_**PL,

**Comment by benzino77** [comment]
It's a typo!!!! Thanks for finding it. It should be just like you described.
 Please include the fix in your PR.

**Comment by benzino77** [comment]
Please update also TRANSLATION.md file.

**Pull request closed without merging**
