### PR TITLE
Fill missing translations from english

### PR DESCRIPTION
**Pull request by drhideg**

### CODE REVIEW

**Comment by benzino77** [comment]
Is it trying to check if other translations (EN is treated as the source of truth) have all the same key:value pairs as EN? If not then it fills the missing key:value pair in particular translation?

**Comment by drhideg** [comment]
Idea comes from #135.

Yes, it is use English as a template to check the the other translation files for the keys, and copy it from english if it is missing.
It can be wierd if you see EN insted of PL if `appBarLangFlag` is missing from Poland translation.  `IntlProvider` handle it well (it will show the key) but where key is used as index at least it will not die.

One thing i forget, and I can do it in the evening is to check foreign keys in the translation files and log to console. With this it can crosscheck English as a template :)

I know a CI/CD setup is a much better solution, I am playing with it on CircleCI.

**Comment by benzino77** [comment]
That's a good idea. I think that it can be done a little bit simpler ;)
I will check it next week and will let you know.

To tell the truth project should have a tests scenarios defined. Every change, commit, merge there should be tests performed (on frontend and backed side) to check whether everything is working as expected. There should be also some CI/CD engine which will check every PR, build docker image, etc.. to prevent situations like in #135.

**Comment by drhideg** [comment]
`Object.assign()` is not scientific enough :)
I wanted to know what is missing if any and fix that. I will not be offended if you do not merge it and do it on your own way, just keep up the good work.

**Comment by benzino77** [comment]
How about this?
```javascript
const allMessages = {
  en: localeEN,
  es: localeES,
  it: localeIT,
  pl: localePL,
  cs: localeCS,
  hu: localeHU,
};

// source of truth
const baseTranslation = 'en';

// get all defined translations other then source of truth
const translations = Object.keys(allMessages).filter(
  (l) => l !== baseTranslation
);

// if particular translation does not have some translation, add the translation from baseTranslation
Object.keys(allMessages[baseTranslation]).forEach((e) => {
  translations.forEach((t) => {
    if (!allMessages[t].hasOwnProperty(e)) {
      allMessages[t][e] = allMessages[baseTranslation][e];
    }
  });
});

export { allMessages };
```

this looks a little bit simpler ,and I think is a little bit more readable.

**Comment by benzino77** [comment]
Having this implemented, there will be no need to update other translations. `EN` as source of truth will be enough for TC to work properly and translator responsible for particular translation will have to add `key:value` pair in a respective translation file.

**I like this!**

**Comment by drhideg** [comment]
Less code is always better :)

I would not be happy to throw away support to not update `key:value` pairs in localization files. After a lot of add/remove/modify it is a serious problem to maintain the translations if the changes are not included, at least the key with an empty value on newly added strings. On modified, i don't know, maybe an underscore in its name or in the current way, overwrite it in english.

**Comment by benzino77** [comment]
It was just a joke ;)
If you approve my proposition of code changes, could you change it on your side so I can merge PR?

**Comment by drhideg** [comment]
Forgot to log missing translations, but it is okay for me.

**Pull request merged**
