### PR TITLE
update boards build defs

### PR DESCRIPTION
**Pull request by Jason2866**
since all use the same code base.

The PR is NOT tested! It should work

### CODE REVIEW

**Comment by benzino77** [comment]
Will it make it incompatible with v10.0.0 and compatible with v10.1.0 and development?

**Comment by benzino77** [comment]
As I can see C3 board is incompatible between 
`v10.0.0 and v10.1.0 `
and also between
`v10.1.0 and development`

I will think about how to deal with it.

**Comment by Jason2866** [comment]
The change should work for master and development

**Comment by Jason2866** [comment]
Better implemented from @benzino77

**Pull request closed without merging**
