### PR TITLE
Multilanguage interface

### PR DESCRIPTION
**Pull request by rapejim**
Implement enhancement #40

- Added react-int and updated socket.io-client libraries
- Implement react-intl library and browser language detection for locale translations
- Added empty translations files for EN, ES and IT languages
- FIX name of app on manifest and TopAppBar
- Set default language to englsih
- Added language flag and comment tooltip on TopAppBar
- Updated tooltip text for language flag on TopAppBar
- Implement react-intl library with FormatedMessage component
- Added multiples translations entries
- FIX translations title of the last step
- FIX minor on spanish translation
- Added auto-select firmware language corresponding to the user's web browser

**NOTE:** _For new interface languages, create a new json file in_ `src/locales/` _folder like_ `en.json` or `es.json` _and add reference to it on_ `src/locales/languages.js`

### CODE REVIEW

**Comment by benzino77** [comment]
Outstanding job! I have to review it. Will be back with questions.

**Comment by bovirus** [comment]
@rapejim 

Thanks for the deveopment.
Why didn't define your brnach as development as for original repository?

**Comment by benzino77** [comment]
@rapejim you have to give me couple of days to review it before merge. For now, I see couple of warnings and errors but it is fixable. There are some places which need _code polishing_ but generally I like it very much!

**Comment by rapejim** [comment]
> @rapejim you have to give me couple of days to review it before merge. For now, I see couple of warnings and errors but it is fixable. There are some places which need _code polishing_ but generally I like it very much!

Don't worry, make me all needed comments or fixes, this is my first React dev, I have programmed more on Angular. But I love learn!!

Thank you for Tasmocompiler it's awesome!

**Comment by rapejim** [comment]
> @rapejim 
> 
> Thanks for the deveopment.
> Why didn't define your brnach as development as for original repository?
> 

@bovirus 
When you make an important new development (like this one), the best practice is to do it in a new branch, 😝

**Comment by bovirus** [comment]
@rapejim 

Your repository should be a fork of tasmocompiler that has branch development channel,.
Then this my request.

**Comment by benzino77** [comment]
I'm almost done, I will merge PR very soon. I have my doubts about key names for translation strings. I'm thinking about something like that:
```javascript
"appBarLangTooltip": "Change web language on browser settings",

"stepSourceTitle": "Tasmota source code",
"stepSourceDescRefresh": "You can refresh source code to the latest state or click NEXT to go to the next step": "You can refresh source code to the latest state or click NEXT to go to the next step",
"stepSourceDescDownload": "Before you go to the next step, you have to download Tasmota source code",

"stepWifiConfTitle": "Wifi configuration",
"stepWifiConfDesc": "Enter SSID and password for your WiFi network",
"stepWifiConfStaticIP": "Static IP",
"stepWifiConfSSID": "Wifi SSID",
"stepWifiConfPassword": "Wifi password",
"stepWifiConfIP": "IP address",
"stepWifiConfMask": "Netmask",
"stepWifiConfGateway": "Gateway",
"stepWifiConfDNS": "DNS server",

```

The main idea is to make those keys MUCH shorter than now. What do you think about it?

**Comment by benzino77** [comment]
> Your repository should be a fork of tasmocompiler that has branch development channel,.
Then this my request.

From tasmocompiler perspective there is no need to have `development` branch. It doesn't matter. It is only important to have `development` branch in Tasmota/Tasmota fork.

PLEASE remember that this is discussion regarding PR.

**Comment by rapejim** [comment]
> I'm almost done, I will merge PR very soon. I have my doubts about key names for translation strings. I'm thinking about something like that:
> 
> ```js
> "appBarLangTooltip": "Change web language on browser settings",
> 
> "stepSourceTitle": "Tasmota source code",
> "stepSourceDescRefresh": "You can refresh source code to the latest state or click NEXT to go to the next step": "You can refresh source code to the latest state or click NEXT to go to the next step",
> "stepSourceDescDownload": "Before you go to the next step, you have to download Tasmota source code",
> 
> "stepWifiConfTitle": "Wifi configuration",
> "stepWifiConfDesc": "Enter SSID and password for your WiFi network",
> "stepWifiConfStaticIP": "Static IP",
> "stepWifiConfSSID": "Wifi SSID",
> "stepWifiConfPassword": "Wifi password",
> "stepWifiConfIP": "IP address",
> "stepWifiConfMask": "Netmask",
> "stepWifiConfGateway": "Gateway",
> "stepWifiConfDNS": "DNS server",
> ```
> 
> The main idea is to make those keys MUCH shorter than now. What do you think about it?

Yes, I prefer a short low-camel-case ids for translations, but with this library if an language json file don't have a this id entry, the text to show will be the id literally. 
Then if the id are a short "words" when you make a new text must translate it on all languages (or copy english version on all other languages files), else the text to show on a new entry will be the id literally.
Using the complete string, you only have worry to include new text entries on en.json file (even this would be optional really, 😝), and the translators can copy it and translate in him/her language file... If you forget add this entry on en.json or other json files, then the library will show the id string complete (that will be the english version).

**Comment by benzino77** [comment]
Sure. I'm aware of this, but it is much more readable in code than long strings.

**Comment by rapejim** [comment]
> Sure. I'm aware of this, but it is much more readable in code than long strings.

Honestly, the change in the source code is minimal. Before you had the complete strings `'XXXX YYYY ZZZZ'` harcoded, and now you have them the same but wrapped in the new component `<FormmatedMessage id='XXXXX YYYY ZZZZ' />`

However for json files and translators, with id like the complete string you only need the file of your language to translate it, you don't have to check the reference stepWifiConfDesc in the file "en.json" to know its meaning in english and then enter the translation in the "es.json" with the same reference.

**Comment by benzino77** [comment]
But I do think that the en.json will be reference for any future translations so there will be short key (more less meaningful ) and string to translate. I have to think about it.

**Comment by bovirus** [comment]
I Think that the length of screen should be compatible with the context of explanation.
Not too short not too long. Depend by context.
Menu/option should be shorter.
Balloon help/explanation of features should be longer

**Comment by rapejim** [comment]
> But I do think that the en.json will be reference for any future translations so there will be short key (more less meaningful ) and string to translate. I have to think about it.

You can just leave it like that, it's working, and keep thinking about it.
If you decide to change it later, it can be done VERY quickly with the "Replace" option of VSCode.
(I could help you if you decide to change it)

**Comment by rapejim** [comment]
@benzino77 
to see these changes (and other new changes) in the docker hub image, it's not automatic, right?
You upload the images manually, true?

**Comment by benzino77** [comment]
Yes it's not automatic. I need to configure CI/CD automation (PR is welcome as usual). It is not done yet because I was waiting for proper Italian translation. I will create new docker images today.

**Pull request merged**
