### PR TITLE
Change sonoff to tasmota folder

### PR DESCRIPTION
**Pull request by rt400**
hi ,
i make a PR that change sonoff folder to tasmota folder

### CODE REVIEW

**Comment by benzino77** [comment]
This change will cause that previous versions of Tasmota (which are available at the last step) will not work, only current development.

**Comment by rt400** [comment]
You have no choice but to separate the versions, or make two folders for development and the other for a formal version

**Comment by benzino77** [comment]
The code has to discover which version is chosen. If this is 6.7.1 or lower then there is an old repository name and source folder. If the version is 6.7.1.1 and higher then this is a new schema. 
[have a look at the changelog](https://github.com/arendst/Tasmota/blob/development/tasmota/_changelog.ino#L27)

There is no need to "split" versions or making two folders.

**Comment by benzino77** [comment]
I'm  thinking about using something like: [version-js](https://www.npmjs.com/package/version-js) to compare and operate with versions.

**Comment by benzino77** [comment]
I've created new TasmoCompiler version which should be fine with Tasmota git repository transitions.

**Pull request closed without merging**
