### PR TITLE
Multiple architectures in the same docker repository

### PR DESCRIPTION
**Pull request by rapejim**
Using diferent tags, you can join multiple architectures images on the same repository.

And the final user only need type `docker run ... benzino77/tasmocompiler` for all architectures.
And it's possible view the diferents tags with version, arch, etc... on the same repository web (better user experience).

An example:
image
https://hub.docker.com/r/rapejim/tasmocompiler/tags

### CODE REVIEW

**Comment by benzino77** [comment]
It is already implemented:
image

**Comment by benzino77** [comment]
Aaaa!! I haven't read your comment carefully! You are probably right. Let me check your proposition

**Comment by rapejim** [comment]
> Aaaa!! I haven't read your comment carefully! You are probably right. Let me check your proposition

😜 (quick read or my bad explanation, don't worry)

You currently use 4 repositories at Docker Hub:
- benzino77/tasmocompiler
- benzino77/tasmocompiler-x86_64
- benzino77/tasmocompiler-arm32v7
- benzino77/tasmocompiler-arm64v8

With these changes, you only need the main repository:
- benzino77/tasmocompiler
And with the labels the different architectures and versions.

**Comment by benzino77** [comment]
You are right it looks much better.

**Comment by benzino77** [comment]
Thanks! I will build next releases of Docker images new way.

**Comment by rapejim** [comment]
> Thanks! I will build next releases of Docker images new way.

Thank you for this amazing WebUI, 😜
Pleasure to help you.

**Comment by benzino77** [comment]
It is pushed to docker repository with new layout.

**Pull request merged**
