### PR TITLE
Added ModbusBridge option and Dutch language

### PR DESCRIPTION
**Pull request by jeroenst**
I added those features and tested them with gitpod.io

### CODE REVIEW

**Comment by jeroenst** [comment]
Tested with gitpod.io and works fine.

**Comment by jeroenst** [comment]
I see you made a group for modbusbridge and modbusbridgetcp. But modbusbridge is mandatory for the modbusbridgetcp option, otherwise build will fail.

**Comment by benzino77** [comment]
Group means: all options from the group, in order they appear in the `group` clause.
So finally it will end up with this:
```c
#ifdef USE_MODBUSBRIDGE
  #undef USE_MODBUSBRIDGE
#endif
#define USE_MODBUSBRIDGE

#ifdef USE_MODBUSBRIDGE_TCP
  #undef USE_MODBUSBRIDGE_TCP
#endif
#define USE_MODBUSBRIDGE_TCP
```

**Comment by jeroenst** [comment]
ok, but some people might want modbus bridge without the TCP option...

**Comment by jeroenst** [comment]
Ok I understand. Maybe it's an idea for the future to add an advanced option giving the option to enable and disable options to the functionalities.

**Pull request merged**
